[2025-01-12T13:43:30.018+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-12T13:43:30.051+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-12T13:43:29.028770+00:00 [queued]>
[2025-01-12T13:43:30.069+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-12T13:43:29.028770+00:00 [queued]>
[2025-01-12T13:43:30.073+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-12T13:43:30.103+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt_model> on 2025-01-12 13:43:29.028770+00:00
[2025-01-12T13:43:30.114+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dbt_dag', 'run_dbt_model', 'manual__2025-01-12T13:43:29.028770+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dbt_dag.py', '--cfg-path', '/tmp/tmpk_6_j3g8']
[2025-01-12T13:43:30.118+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask run_dbt_model
[2025-01-12T13:43:30.120+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-12T13:43:30.121+0000] {standard_task_runner.py:72} INFO - Started process 668 to run task
[2025-01-12T13:43:30.171+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-12T13:43:29.028770+00:00 [running]> on host 10a7333bcdf9
[2025-01-12T13:43:30.257+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dbt_dag' AIRFLOW_CTX_TASK_ID='run_dbt_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T13:43:29.028770+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T13:43:29.028770+00:00'
[2025-01-12T13:43:30.258+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-12T13:43:37.611+0000] {logging_mixin.py:190} INFO - 13:43:34  Running with dbt=1.6.1
13:43:34  Registered adapter: postgres=1.6.1
13:43:36  Found 4 models, 2 seeds, 2 sources, 0 exposures, 0 metrics, 464 macros, 0 groups, 0 semantic models
13:43:36  
13:43:36  Concurrency: 1 threads (target='dev')
13:43:36  
13:43:36  1 of 1 START sql table model jin_schema.my_first_dbt_model ..................... [RUN]
13:43:36  1 of 1 OK created sql table model jin_schema.my_first_dbt_model ................ [SELECT 2 in 0.16s]
13:43:36  
13:43:36  Finished running 1 table model in 0 hours 0 minutes and 0.30 seconds (0.30s).
13:43:36  
13:43:36  Completed successfully
13:43:36  
13:43:36  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-01-12T13:43:37.613+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-12T13:43:37.624+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-12T13:43:37.626+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dbt_dag, task_id=run_dbt_model, run_id=manual__2025-01-12T13:43:29.028770+00:00, execution_date=20250112T134329, start_date=20250112T134330, end_date=20250112T134337
[2025-01-12T13:43:37.626+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: slack_success_callback
[2025-01-12T13:43:37.628+0000] {taskinstance.py:1567} ERROR - Error in callback at index 0: slack_success_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1565, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/my_first_dbt_dag.py", line 34, in slack_success_callback
    f"*Log URL*: {context.get('dag_run').log_url}"
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DagRun' object has no attribute 'log_url'
[2025-01-12T13:43:37.699+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-12T13:43:37.723+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-12T13:43:37.727+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
