[2025-01-12T13:31:01.112+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-12T13:31:01.129+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-12T13:30:59.744415+00:00 [queued]>
[2025-01-12T13:31:01.137+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-12T13:30:59.744415+00:00 [queued]>
[2025-01-12T13:31:01.137+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-12T13:31:01.153+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_dbt_model> on 2025-01-12 13:30:59.744415+00:00
[2025-01-12T13:31:01.161+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dbt_dag', 'run_dbt_model', 'manual__2025-01-12T13:30:59.744415+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dbt_dag.py', '--cfg-path', '/tmp/tmp3qu45kd2']
[2025-01-12T13:31:01.163+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask run_dbt_model
[2025-01-12T13:31:01.164+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=204) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-12T13:31:01.165+0000] {standard_task_runner.py:72} INFO - Started process 206 to run task
[2025-01-12T13:31:01.207+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dbt_dag.run_dbt_model manual__2025-01-12T13:30:59.744415+00:00 [running]> on host 10a7333bcdf9
[2025-01-12T13:31:01.286+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_first_dbt_dag' AIRFLOW_CTX_TASK_ID='run_dbt_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T13:30:59.744415+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T13:30:59.744415+00:00'
[2025-01-12T13:31:01.287+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-12T13:31:06.215+0000] {logging_mixin.py:190} INFO - 13:31:04  Running with dbt=1.6.1
13:31:04  Registered adapter: postgres=1.6.1
13:31:04  Found 4 models, 2 seeds, 2 sources, 0 exposures, 0 metrics, 464 macros, 0 groups, 0 semantic models
13:31:04  
13:31:04  Concurrency: 1 threads (target='dev')
13:31:04  
13:31:04  1 of 1 START sql table model jin_schema.my_first_dbt_model ..................... [RUN]
13:31:04  1 of 1 OK created sql table model jin_schema.my_first_dbt_model ................ [SELECT 2 in 0.14s]
13:31:05  
13:31:05  Finished running 1 table model in 0 hours 0 minutes and 0.25 seconds (0.25s).
13:31:05  
13:31:05  Completed successfully
13:31:05  
13:31:05  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-01-12T13:31:06.216+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-12T13:31:06.227+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-12T13:31:06.227+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dbt_dag, task_id=run_dbt_model, run_id=manual__2025-01-12T13:30:59.744415+00:00, execution_date=20250112T133059, start_date=20250112T133101, end_date=20250112T133106
[2025-01-12T13:31:06.247+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-12T13:31:06.263+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-12T13:31:06.265+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
